// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: defaultValue.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price     float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Price2    float32 `protobuf:"fixed32,3,opt,name=price2,proto3" json:"price2,omitempty"`
	Price3    int64   `protobuf:"varint,4,opt,name=price3,proto3" json:"price3,omitempty"`
	Price4    int32   `protobuf:"varint,5,opt,name=price4,proto3" json:"price4,omitempty"`
	Price5    uint32  `protobuf:"varint,6,opt,name=price5,proto3" json:"price5,omitempty"`
	Price6    uint64  `protobuf:"varint,7,opt,name=price6,proto3" json:"price6,omitempty"`
	Done      bool    `protobuf:"varint,8,opt,name=done,proto3" json:"done,omitempty"`
	BookBytes []byte  `protobuf:"bytes,9,opt,name=bookBytes,proto3" json:"bookBytes,omitempty"`
}

func (x *DefaultRequest) Reset() {
	*x = DefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaultValue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultRequest) ProtoMessage() {}

func (x *DefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_defaultValue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultRequest.ProtoReflect.Descriptor instead.
func (*DefaultRequest) Descriptor() ([]byte, []int) {
	return file_defaultValue_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DefaultRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DefaultRequest) GetPrice2() float32 {
	if x != nil {
		return x.Price2
	}
	return 0
}

func (x *DefaultRequest) GetPrice3() int64 {
	if x != nil {
		return x.Price3
	}
	return 0
}

func (x *DefaultRequest) GetPrice4() int32 {
	if x != nil {
		return x.Price4
	}
	return 0
}

func (x *DefaultRequest) GetPrice5() uint32 {
	if x != nil {
		return x.Price5
	}
	return 0
}

func (x *DefaultRequest) GetPrice6() uint64 {
	if x != nil {
		return x.Price6
	}
	return 0
}

func (x *DefaultRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *DefaultRequest) GetBookBytes() []byte {
	if x != nil {
		return x.BookBytes
	}
	return nil
}

type DefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DefaultResponse) Reset() {
	*x = DefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defaultValue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResponse) ProtoMessage() {}

func (x *DefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_defaultValue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResponse.ProtoReflect.Descriptor instead.
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return file_defaultValue_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_defaultValue_proto protoreflect.FileDescriptor

var file_defaultValue_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x33, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x34, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x35, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x35, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x36, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0x41, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x0f, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_defaultValue_proto_rawDescOnce sync.Once
	file_defaultValue_proto_rawDescData = file_defaultValue_proto_rawDesc
)

func file_defaultValue_proto_rawDescGZIP() []byte {
	file_defaultValue_proto_rawDescOnce.Do(func() {
		file_defaultValue_proto_rawDescData = protoimpl.X.CompressGZIP(file_defaultValue_proto_rawDescData)
	})
	return file_defaultValue_proto_rawDescData
}

var file_defaultValue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_defaultValue_proto_goTypes = []interface{}{
	(*DefaultRequest)(nil),  // 0: DefaultRequest
	(*DefaultResponse)(nil), // 1: DefaultResponse
}
var file_defaultValue_proto_depIdxs = []int32{
	0, // 0: DefaultService.GetDefault:input_type -> DefaultRequest
	1, // 1: DefaultService.GetDefault:output_type -> DefaultResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_defaultValue_proto_init() }
func file_defaultValue_proto_init() {
	if File_defaultValue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_defaultValue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_defaultValue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_defaultValue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_defaultValue_proto_goTypes,
		DependencyIndexes: file_defaultValue_proto_depIdxs,
		MessageInfos:      file_defaultValue_proto_msgTypes,
	}.Build()
	File_defaultValue_proto = out.File
	file_defaultValue_proto_rawDesc = nil
	file_defaultValue_proto_goTypes = nil
	file_defaultValue_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DefaultServiceClient is the client API for DefaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DefaultServiceClient interface {
	GetDefault(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*DefaultResponse, error)
}

type defaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDefaultServiceClient(cc grpc.ClientConnInterface) DefaultServiceClient {
	return &defaultServiceClient{cc}
}

func (c *defaultServiceClient) GetDefault(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*DefaultResponse, error) {
	out := new(DefaultResponse)
	err := c.cc.Invoke(ctx, "/DefaultService/GetDefault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultServiceServer is the server API for DefaultService service.
type DefaultServiceServer interface {
	GetDefault(context.Context, *DefaultRequest) (*DefaultResponse, error)
}

// UnimplementedDefaultServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDefaultServiceServer struct {
}

func (*UnimplementedDefaultServiceServer) GetDefault(context.Context, *DefaultRequest) (*DefaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefault not implemented")
}

func RegisterDefaultServiceServer(s *grpc.Server, srv DefaultServiceServer) {
	s.RegisterService(&_DefaultService_serviceDesc, srv)
}

func _DefaultService_GetDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultServiceServer).GetDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DefaultService/GetDefault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultServiceServer).GetDefault(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DefaultService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DefaultService",
	HandlerType: (*DefaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDefault",
			Handler:    _DefaultService_GetDefault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defaultValue.proto",
}
